# testing

matrix:
  include:
    - language: python
      dist: xenial
      sudo: required
      python: "3.7"
      services:
        - docker

env:
  global:
    - CIBW_BUILD="cp37-*"
      #- CIBW_TEST_COMMAND="echo 'in subshell' && set -o && false"
    - CIBW_TEST_COMMAND="echo 'bash version' && bash -version && echo 'in subshell' && set -o && echo 'shopt' && shopt && python -m unittest discover -f -v -s {project}/tests"

script:
  #- pip install -e 
  #git+git://github.com/joerick/cibuildwheel.git@master#egg=cibuildwheel
  - pip install -e git+git://github.com/joerick/cibuildwheel.git@ee2a90880a2d7c3a9b3ac953e2aa2ae50187e51b#egg=cibuildwheel
  - cibuildwheel --output-dir wheelhouse
  - ls wheelhouse
